train:
  loss_weights:
    rot: 1.0
    pos: 1.0
    seq: 1.0
  max_epochs: 1000
  val_freq: 10
  batch_size: 16
  seed: 2022
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 5.e-6