train:
  loss_weights:
    rot: 1.0
    pos: 1.0
    seq: 0.5
  max_epochs: 1000
  val_freq: 5
  batch_size: 4
  seed: 2022
  max_len: 300
  path: ./processed_500
  num_layers: 6
  early_stop_patience: 100
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 5.e-6